### ISSUE TITLE
"Community consultation needed for proposed new tag" remains for some

### ISSUE THREAD

**Issue by matkoniecz** [cyclestreets/tflcid-conversion#43] opened 2022-08-04 20:14 UTC
For example https://bikedata.cyclestreets.net/tflcid/conversion/#trf_sinuso https://bikedata.cyclestreets.net/tflcid/conversion/#sig_early https://bikedata.cyclestreets.net/tflcid/conversion/#prk_carr https://bikedata.cyclestreets.net/tflcid/conversion/#prk_wheel

It is not a blocker, as long as it will be skipped from import for now

**Comment by mvl22** [comment] 2022-09-26 12:02
> https://bikedata.cyclestreets.net/tflcid/conversion/#sig_early

This (Early Release signals) is covered in #24.

**Comment by mvl22** [comment] 2022-09-26 13:13
> https://bikedata.cyclestreets.net/tflcid/conversion/#prk_wheel

These are going in as upright_stands already.

There was no previous feedback on this, so I felt this pretty minor matter for a pretty small number of cases was fine, and [Taginfo shows](https://taginfo.openstreetmap.org/keys/bicycle_parking#values) that where there is an undefined value, people put in something reasonable.

**Comment by mvl22** [comment] 2022-09-26 13:16
> https://bikedata.cyclestreets.net/tflcid/conversion/#prk_carr

Duplicate of #14.

This got [implemented](https://github.com/cyclestreets/tflcid-conversion/blob/e90ef73915111d91dde7554bf2faaeb9bb33ed4e/readers/parking.rb#L83) as `on_carriageway=yes`.

**Comment by mvl22** [comment] 2022-09-26 13:23
> https://bikedata.cyclestreets.net/tflcid/conversion/#trf_sinuso

Looks like this [already went in](https://github.com/cyclestreets/tflcid-conversion/blob/68fb091ad20e4a465d7f3faad1059c66dfc01ddf/readers/traffic_calming_bumps.rb#L32,L52) as sinusoidal='yes' as again there was no more detailed feedback, but I'm not clear from the code. Again seems a pretty minor thing.

Action @systemed:

- Could you check sinusoidal='yes' is implemented - there's a double-equals there and then a comment later implies it's not then used.

**Closed as completed** 2022-09-30 13:37 UTC

**Comment by systemed** [comment] 2022-09-30 13:57
Good spot on the double-equals - fixed!

I've also implemented https://github.com/cyclestreets/tflcid-conversion/commit/cce0e7869f2155401bb4eeec68b7476cf07ffacb so we don't write anything that doesn't need to be changed (c. 2500 features). I've counted merely adding `sinusoidal=yes` as this, because going through 2500 features just to add `sinusoidal=yes` isn't a sensible use of anyone's time.
